### ISSUE TITLE
String URL not returned.

### ISSUE THREAD

**Issue by arindammitra06** [Deepjyoti120/imagekit_io#1]
The plugin works perfect. Just to point out, the return is no more String Url. it returns the json response. Please fix that

then((String url) {
    // Get your uploaded Image file link from ImageKit.io
    //then save it anywhere you want. For Example- Firebase, MongoDB etc.
    if (kDebugMode) {
      print(url); // your Uploaded Image/Video Link From Imagekit
 }

**Comment by Deepjyoti120** [comment]
Upgrade to imagekit_io: ^0.0.3
